### ISSUE TITLE
这个生成的txt直接复制到markdown中 就被压缩了 不换行了

### ISSUE THREAD

**Issue by zjy2931** [lecepin/dir-tree#1]
📁user
├─ 📄.gitignore
├─ 📄babel.config.js
├─ 📄mainfest.js
├─ 📄package-lock.json
├─ 📄package.json
├─ 📄postcss.config.js
├─ 📄project.config.js
├─ 📄project.config.json
├─ 📄project.private.config.json
├─ 📄README.md
├─ 📄tsconfig.json
├─ 📄vue.config.js
├─ 📄版本更新记录.txt
├─ 📁public
│  └─ 📄index.html
├─ 📁.git
└─ 📁src
   ├─ 📄App.vue
   ├─ 📄changelog.md
   ├─ 📄index.html
   ├─ 📄LICENSE
   ├─ 📄main.js
   ├─ 📄manifest.json
   ├─ 📄package-lock.json
   ├─ 📄package.json
   ├─ 📄pages.json
   ├─ 📄README.md
   ├─ 📄template.h5.html
   ├─ 📄uni.scss
   ├─ 📁asset
   │  ├─ 📄icon.css
   │  └─ 📄icon_sprites_1.0.0.png
   ├─ 📁common
   │  ├─ 📄airport.js
   │  ├─ 📄config.js
   │  ├─ 📄configVersion.js
   │  ├─ 📄echarts.min.js
   │  ├─ 📄env.js
   │  ├─ 📄globalData.js
   │  ├─ 📄graceChecker.js
   │  ├─ 📄html-parser.js
   │  ├─ 📄mqtt.js
   │  ├─ 📄permission.js
   │  ├─ 📄request.js
   │  ├─ 📄uni-nvue.css
   │  ├─ 📄uni.css
   │  ├─ 📄util.js
   │  └─ 📄wechat.js
   ├─ 📁page_onlineDoc
   │  ├─ 📄articleList.vue
   │  ├─ 📄buyConsultation.vue
   │  ├─ 📄docDetail.vue
   │  ├─ 📄index.vue
   │  ├─ 📄myService.vue
   │  ├─ 📄serviceChat.vue
   │  └─ 📄submitOrder.vue
   ├─ 📁page_readReport
   │  ├─ 📄buyConsultation.vue
   │  ├─ 📄docDetail.vue
   │  └─ 📄index.vue
   ├─ 📁router
   │  └─ 📄router.js
   ├─ 📁store
   │  └─ 📄index.js
   ├─ 📁windows
   │  ├─ 📄left-window.vue
   │  └─ 📄top-window.vue
   ├─ 📁hybrid
   │  └─ 📁html
   ├─ 📁pages
   │  ├─ 📄addPatient.vue
   │  ├─ 📄choosePatient.vue
   │  ├─ 📄followDoctor.vue
   │  ├─ 📄index.vue
   │  ├─ 📄index2.vue
   │  ├─ 📄login.vue
   │  ├─ 📄mine.vue
   │  ├─ 📄redirect.vue
   │  ├─ 📄userAgreement.vue
   │  └─ 📁mine
   ├─ 📁page_tool
   │  ├─ 📄awaitingDelivery.vue
   │  ├─ 📄babyMusic.vue
   │  ├─ 📄babyMusicSearch.vue
   │  ├─ 📄babyWeightResult.vue
   │  ├─ 📄estimateBabyWeight.vue
   │  ├─ 📄movementsList.vue
   │  ├─ 📄pregnantCalendar.vue
   │  ├─ 📄pregnantDetail.vue
   │  ├─ 📄recordMovements.vue
   │  ├─ 📄recordWeight.vue
   │  ├─ 📄vaccinesDetail.vue
   │  ├─ 📄vaccinesList.vue
   │  └─ 📁components
   ├─ 📁wxcomponents
   │  └─ 📁imageCropper
   ├─ 📁components
   │  ├─ 📄choose-patient-pop.vue
   │  ├─ 📄circleProgress.vue
   │  ├─ 📄confirm-modal.vue
   │  ├─ 📄curve-sugar.vue
   │  ├─ 📄empty.vue
   │  ├─ 📄header-h5.vue
   │  ├─ 📄mine-date-picker.vue
   │  ├─ 📄musicBtn.vue
   │  ├─ 📄navHeader.vue
   │  ├─ 📄navHeader_calendar.vue
   │  ├─ 📄normal-toolTip.vue
   │  ├─ 📄pay-result-pop.vue
   │  ├─ 📄recordTimeBtn.vue
   │  ├─ 📄registerPop.vue
   │  ├─ 📄remind-pop.vue
   │  ├─ 📄updateAppPop.vue
   │  ├─ 📁city-picker
   │  ├─ 📁loginPop
   │  ├─ 📁mine-checkbox
   │  ├─ 📁mine-picker
   │  ├─ 📁mine-radio
   │  ├─ 📁mine-tabs
   │  ├─ 📁tab-pages
   │  ├─ 📁amap-wx
   │  └─ 📁minTextarea
   ├─ 📁platforms
   │  └─ 📁app-plus
   ├─ 📁static
   │  ├─ 📄customicons.css
   │  ├─ 📄customicons.ttf
   │  ├─ 📄iconfont.css
   │  ├─ 📄iconfont.ttf
   │  ├─ 📄uni.ttf
   │  ├─ 📁images
   │  └─ 📁plugin
   ├─ 📁page_bloodSugar
   │  ├─ 📄article.vue
   │  ├─ 📄bindingMeter.vue
   │  ├─ 📄bindRecord.vue
   │  ├─ 📄chooseFood.vue
   │  ├─ 📄foodDetail.vue
   │  ├─ 📄helpPage.vue
   │  ├─ 📄historyRecord.vue
   │  ├─ 📄index.vue
   │  ├─ 📄questionPage.vue
   │  ├─ 📄recordTotal.vue
   │  ├─ 📄register.vue
   │  ├─ 📄searchFood.vue
   │  ├─ 📄sugarCurve.vue
   │  ├─ 📄sugarStatic.vue
   │  ├─ 📄userAgreement.vue
   │  ├─ 📄weightCurve.vue
   │  ├─ 📁components
   │  ├─ 📁service
   │  └─ 📁static
   ├─ 📁uni_modules
   │  ├─ 📁rhliu-mqttjs
   │  ├─ 📁uni-badge
   │  ├─ 📁uni-card
   │  ├─ 📁uni-collapse
   │  ├─ 📁uni-combox
   │  ├─ 📁uni-data-checkbox
   │  ├─ 📁uni-data-picker
   │  ├─ 📁uni-dateformat
   │  ├─ 📁uni-drawer
   │  ├─ 📁uni-easyinput
   │  ├─ 📁uni-fab
   │  ├─ 📁uni-file-picker
   │  ├─ 📁uni-forms
   │  ├─ 📁uni-grid
   │  ├─ 📁uni-group
   │  ├─ 📁uni-icons
   │  ├─ 📁uni-indexed-list
   │  ├─ 📁uni-link
   │  ├─ 📁uni-list
   │  ├─ 📁uni-nav-bar
   │  ├─ 📁uni-notice-bar
   │  ├─ 📁uni-number-box
   │  ├─ 📁uni-rate
   │  ├─ 📁uni-row
   │  ├─ 📁uni-scss
   │  ├─ 📁uni-segmented-control
   │  ├─ 📁uni-steps
   │  ├─ 📁uni-swipe-action
   │  ├─ 📁uni-swiper-dot
   │  ├─ 📁uni-table
   │  ├─ 📁uni-tag
   │  ├─ 📁uni-title
   │  ├─ 📁uni-transition
   │  ├─ 📁uni-calendar
   │  ├─ 📁uni-countdown
   │  ├─ 📁uni-datetime-picker
   │  ├─ 📁uni-fav
   │  ├─ 📁uni-goods-nav
   │  ├─ 📁uni-load-more
   │  ├─ 📁uni-pagination
   │  ├─ 📁uni-popup
   │  ├─ 📁uni-search-bar
   │  └─ 📁uni-upgrade-center-app
   └─ 📁js_sdk
      ├─ 📁hhyang-uni-simple-router
      └─ 📁uniapp-router-view-loader

**Comment by lecepin** [comment]
```
放在这种代码标签内
```

![image](https://github.com/lecepin/dir-tree/assets/11046969/1e910440-900d-4597-b80b-28fa024a57fb)
